# Reusable workflow for packaging
name: Pack

on:
  workflow_call:
    inputs:
      build-configuration:
        description: 'The build configuration for the project'
        required: true
        type: string
      version:
        description: 'SemVer2 version string. Do not include a leading "v" prefix. (e.g. 1.0.0-beta.0)'
        required: true
        type: string
    
jobs:
  pack:
    # The type of runner that the job will run on
    runs-on: windows-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      # Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      
      # Download artifacts
      - name: Download artifacts
        uses: actions/download-artifact@master
        with:
          name: build-artifact
          path: ./.artifacts/bin/
      
      # Create the package
      - name: Pack
        run: >
          dotnet pack
          --no-build
          --include-symbols
          --configuration ${{ inputs.build-configuration }}
          --property:Version=${{ inputs.version }}
          --property:OutputPath=./.artifacts/bin/
          --property:PackageOutputPath=./.artifacts/pack/
      
      # Upload artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: pack-artifact
          path: ./.artifacts/pack/
          retention-days: 5
      
